        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 03 21:40:36 2021
        MODULE SUM_DENSITY__genmod
          INTERFACE 
            SUBROUTINE SUM_DENSITY(NTOTAL,HSML,MASS,NIAC,PAIR_I,PAIR_J,W&
     &,ITYPE,RHO,ITIMESTEP)
              INTEGER(KIND=4) :: NTOTAL
              REAL(KIND=8) :: HSML(100000)
              REAL(KIND=8) :: MASS(100000)
              INTEGER(KIND=4) :: NIAC
              INTEGER(KIND=4) :: PAIR_I(10000000)
              INTEGER(KIND=4) :: PAIR_J(10000000)
              REAL(KIND=8) :: W(10000000)
              INTEGER(KIND=4) :: ITYPE(100000)
              REAL(KIND=8) :: RHO(100000)
              INTEGER(KIND=4) :: ITIMESTEP
            END SUBROUTINE SUM_DENSITY
          END INTERFACE 
        END MODULE SUM_DENSITY__genmod
