        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 21 16:19:35 2021
        MODULE TIME_ELAPSED__genmod
          INTERFACE 
            SUBROUTINE TIME_ELAPSED(S)
              REAL(KIND=8) :: S
            END SUBROUTINE TIME_ELAPSED
          END INTERFACE 
        END MODULE TIME_ELAPSED__genmod
