        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 03 21:40:41 2021
        MODULE TIME_ELAPSED__genmod
          INTERFACE 
            SUBROUTINE TIME_ELAPSED(S)
              REAL(KIND=8) :: S
            END SUBROUTINE TIME_ELAPSED
          END INTERFACE 
        END MODULE TIME_ELAPSED__genmod
