        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 05 10:12:23 2021
        MODULE TIME_PRINT__genmod
          INTERFACE 
            SUBROUTINE TIME_PRINT
            END SUBROUTINE TIME_PRINT
          END INTERFACE 
        END MODULE TIME_PRINT__genmod
