        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 21 16:19:34 2021
        MODULE TIME_PRINT__genmod
          INTERFACE 
            SUBROUTINE TIME_PRINT
            END SUBROUTINE TIME_PRINT
          END INTERFACE 
        END MODULE TIME_PRINT__genmod
