        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 05 10:12:29 2021
        MODULE TIME_ELAPSED__genmod
          INTERFACE 
            SUBROUTINE TIME_ELAPSED(S)
              REAL(KIND=8) :: S
            END SUBROUTINE TIME_ELAPSED
          END INTERFACE 
        END MODULE TIME_ELAPSED__genmod
