        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 03 21:40:34 2021
        MODULE TIME_PRINT__genmod
          INTERFACE 
            SUBROUTINE TIME_PRINT
            END SUBROUTINE TIME_PRINT
          END INTERFACE 
        END MODULE TIME_PRINT__genmod
